"""PhoenixGuard — Prompt Optimizer Agent (Phase 6).

Analyzes recent traces and errors alongside the current agent prompt to locate
weaknesses and output a rewritten, optimized system instruction.
"""

from __future__ import annotations

import json
import logging
import os
from typing import Any, Dict, List, Optional

from google import genai
from google.genai import types

# Set up logging
logger = logging.getLogger(__name__)


class PromptOptimizer:
    """Agent that analyzes agent prompts and optimizes them based on trace feedback."""

    def __init__(self, gemini_client: Optional[genai.Client] = None) -> None:
        self.client = gemini_client or self._init_client()
        self.model = os.getenv("PHOENIXGUARD_MODEL", "gemini-2.5-flash")
        logger.info("PromptOptimizer initialized with model: %s", self.model)

    def _init_client(self) -> Optional[genai.Client]:
        """Initialize the Google GenAI Client using available environment keys."""
        api_key = os.getenv("GENAI_API_KEY") or os.getenv("GOOGLE_API_KEY") or os.getenv("GEMINI_API_KEY")
        if not api_key:
            logger.warning("No Gemini API key found in env. Prompt optimization will fall back to default.")
            return None
        try:
            return genai.Client(api_key=api_key)
        except Exception as exc:
            logger.warning("Failed to initialize Gemini client: %s. Falling back to default.", exc)
            return None

    def optimize_prompt(
        self, traces: List[Dict[str, Any]], current_prompt: str
    ) -> Dict[str, Any]:
        """Review recent traces and current prompt to output weaknesses and a rewritten prompt.

        Args:
            traces: List of trace dictionaries.
            current_prompt: The current system instruction string.

        Returns:
            Dict containing: weaknesses (list), prompt_improvements (list), rewritten_prompt (str).
        """
        # Formulate default/fallback response in case LLM is unreachable or no key is present
        fallback = {
            "weaknesses": [
                "System instructions lack specific validation requirements for tool outputs.",
                "Error fallback behavior is not explicitly defined in instructions, causing LLM hallucination on tool failures."
            ],
            "prompt_improvements": [
                "Add explicit handling and messaging guidelines for tool error messages.",
                "Detail formatting rules for numeric values returned by system metrics tools."
            ],
            "rewritten_prompt": (
                f"{current_prompt}\n\n"
                "## Additional Robustness Guidelines\n"
                "- If a tool returns an error structure (e.g. 'error' key present), report the error details "
                "honestly. Do not make up successful metrics.\n"
                "- Always verify that all numbers extracted from get_system_health are outputted with "
                "their appropriate unit labels (%, GB, ms)."
            )
        }

        # Check if client or traces are empty
        if self.client is None or not traces:
            logger.info("Returning fallback prompt optimization (no LLM connection or empty traces).")
            return fallback

        # Clean traces for prompt to avoid token overflow
        clean_traces_summary = []
        for t in traces:
            trace_summary = {
                "trace_id": t.get("trace_id"),
                "token_count_total": t.get("token_count_total"),
                "spans": [
                    {
                        "name": s.get("name"),
                        "span_kind": s.get("span_kind"),
                        "status_code": s.get("status_code"),
                        "status_message": s.get("status_message")
                    }
                    for s in (t.get("spans", []) or [])
                ]
            }
            clean_traces_summary.append(trace_summary)

        prompt = f"""\
You are an expert Prompt Engineer and AI Observability Agent. Your task is to optimize the system prompt of an LLM agent by analyzing its recent execution traces.

Below is the current system prompt template used by the agent:

## Current System Prompt
{current_prompt}

Below are the recent traces generated by the agent (some of which may have failed or encountered latency/token consumption issues):

## Recent Traces
{json.dumps(clean_traces_summary, indent=2)}

## Instructions
Analyze the traces to identify:
1. Instruction gaps (e.g. why did the agent fail to call tools, call tools with incorrect parameters, or hallucinate answers?).
2. Weaknesses in the prompt that can be improved.
3. Suggest improvements and rewrite the system prompt to be more robust, performant, and resilient to errors.

Your response MUST be a single JSON object with EXACTLY these three keys:
- "weaknesses": A JSON array of strings, listing identified weaknesses.
- "prompt_improvements": A JSON array of strings, listing concrete changes made.
- "rewritten_prompt": The full rewritten system prompt incorporating all improvements.

Return ONLY valid JSON. Do not include markdown code block formatting (such as ```json) in your response.
"""

        try:
            response = self.client.models.generate_content(
                model=self.model,
                contents=prompt,
                config=types.GenerateContentConfig(
                    response_mime_type="application/json",
                    temperature=0.2,
                )
            )

            response_text = response.text.strip() if response.text else "{}"
            # Strip potential code blocks
            if response_text.startswith("```"):
                if response_text.startswith("```json"):
                    response_text = response_text[7:]
                else:
                    response_text = response_text[3:]
                if response_text.endswith("```"):
                    response_text = response_text[:-3]
                response_text = response_text.strip()

            result = json.loads(response_text)
            required_keys = ["weaknesses", "prompt_improvements", "rewritten_prompt"]
            if all(k in result for k in required_keys):
                logger.info("PromptOptimizer completed successfully. Found %d weaknesses.", len(result["weaknesses"]))
                return result
            else:
                logger.warning("PromptOptimizer result missing required keys. Falling back to default.")

        except Exception as exc:
            logger.error("Prompt optimization failed: %s. Returning fallback optimization.", exc)

        return fallback
